In [59]:
x = rand(1000)
A = rand(1000, 1000)
b = A * x

inv_x = inv(A) * b

1000-element Array{Float64,1}:
 0.5331525936370198  
 0.7341899424514651  
 0.6870253640037447  
 0.1987322056558014  
 0.653279364263085   
 0.19946274155734045 
 0.1744658005110722  
 0.31867093861024287 
 0.24962703339345182 
 0.04442353683681688 
 0.1123924424073568  
 0.7720311506388171  
 0.3261919810440901  
 ⋮                   
 0.4492750801391594  
 0.7267356868142052  
 0.8539457304715086  
 0.44701933311768016 
 0.4598473792496591  
 0.4081238767095279  
 0.6006500487717492  
 0.04094832911492574 
 0.0653847829369596  
 0.24805584791165813 
 0.5623740006764564  
 0.027238505901500787

In [60]:
time_inv = @elapsed inv(A) * b

0.162292942

In [61]:
x

1000-element Array{Float64,1}:
 0.5331525936371582 
 0.7341899424515812 
 0.687025364003877  
 0.19873220565604544
 0.6532793642627677 
 0.1994627415575887 
 0.17446580051131777
 0.3186709386096096 
 0.2496270333936783 
 0.04442353683743394
 0.11239244240793411
 0.7720311506394895 
 0.32619198104359937
 ⋮                  
 0.4492750801390435 
 0.7267356868146013 
 0.8539457304710198 
 0.4470193331169441 
 0.45984737924934005
 0.40812387670897254
 0.6006500487719701 
 0.04094832911491508
 0.06538478293724315
 0.2480558479121604 
 0.5623740006758435 
 0.0272385059017195 

In [62]:
slash_x = A\b

1000-element Array{Float64,1}:
 0.533152593637095   
 0.7341899424518088  
 0.6870253640037324  
 0.19873220565592792 
 0.6532793642629394  
 0.19946274155759133 
 0.1744658005111902  
 0.3186709386097471  
 0.24962703339368086 
 0.044423536837581525
 0.11239244240759749 
 0.7720311506390916  
 0.3261919810435866  
 ⋮                   
 0.4492750801396776  
 0.7267356868140932  
 0.8539457304714447  
 0.4470193331170585  
 0.45984737924991    
 0.40812387670883876 
 0.6006500487718286  
 0.04094832911492502 
 0.06538478293729304 
 0.24805584791250598 
 0.5623740006757256  
 0.027238505901547652

In [63]:
time_slash = @elapsed A\b

0.021188949

In [64]:
using (LinearAlgebra)
fact = factorize(A)
fact_x = fact\b
time_fact = @elapsed fact\b

0.000631896

In [51]:
fact_x

1000-element Array{Float64,1}:
 0.5961057630585528 
 0.7853755600975466 
 0.1075323775501299 
 0.890944140253903  
 0.9390740439403974 
 0.1892331473305809 
 0.5384767525646195 
 0.30614617277128103
 0.6178923162942277 
 0.07182460668862863
 0.28274174723563733
 0.2745738022048082 
 0.6615940331861284 
 ⋮                  
 0.863159618249339  
 0.7395071550424225 
 0.7956833688246737 
 0.7977514600837157 
 0.35876189690118426
 0.37012947964434356
 0.5919270847775694 
 0.6982950923843892 
 0.6610236235222815 
 0.6342659342949994 
 0.613860769211796  
 0.3016786549505876 

In [52]:
temp_inv = x - inv_x
sqrt(dot(temp_inv, temp_inv))

1.9420045018554646e-11

In [54]:
temp_slash = x - slash_x
sqrt(dot(temp_slash, temp_slash))

1.1760365027851747e-11

In [29]:
temp_fact = x - fact_x
sqrt(dot(temp_fact, temp_fact))

1.6177429602858383e-11

In [3]:
using CSV
using DataFrames
using Statistics
using Plots
using Polynomials

input="resultlab3.csv"
myData=DataFrame()
myData=CSV.read(input, delim=",")
dfg2=by(myData, :SIZE, avg_n_time=:NAIVE => mean, avg_b_time=:BETTER => mean, avg_g_time=:GSL => mean)

y=dfg2[:avg_n_time]
x=dfg2[:SIZE]

fitNaive=polyfit(x,y,3)

Poly(-1.6400650642156497e7 + 476006.82966026437*x - 3171.7629790068563*x^2 + 10.713250877618268*x^3)

In [4]:
len = length(x)

A = zeros(len, 4)
A[:,1] = x.^3
A[:,2] = x.^2
A[:,3] = x
A[:,4] = ones(len)

A

19×4 Array{Float64,2}:
  15625.0           625.0   25.0  1.0
 125000.0          2500.0   50.0  1.0
 421875.0          5625.0   75.0  1.0
      1.0e6       10000.0  100.0  1.0
      1.95313e6   15625.0  125.0  1.0
      3.375e6     22500.0  150.0  1.0
      5.35938e6   30625.0  175.0  1.0
      8.0e6       40000.0  200.0  1.0
      1.13906e7   50625.0  225.0  1.0
      1.5625e7    62500.0  250.0  1.0
      2.07969e7   75625.0  275.0  1.0
      2.7e7       90000.0  300.0  1.0
      3.43281e7  105625.0  325.0  1.0
      4.2875e7   122500.0  350.0  1.0
      5.27344e7  140625.0  375.0  1.0
      6.4e7      160000.0  400.0  1.0
      7.67656e7  180625.0  425.0  1.0
      9.1125e7   202500.0  450.0  1.0
      1.07172e8  225625.0  475.0  1.0

In [5]:
A\y

4-element Array{Float64,1}:
     10.713250877618268   
  -3171.7629790068563     
 476006.82966026437       
     -1.6400650642156497e7